### ISSUE TITLE
支持新的 TOML 配置格式

### ISSUE THREAD

**Issue by icodesign** [Potatso/Management#67]
```toml
[profile.my]
name = "My Profile"
proxy = "hk"
ruleset = [
  "direct",
  "google",
  "cloudset.potatso.telegram",
]

[proxy.hk]
ip = "10.0.0.1"
remark = "SS HK"

[proxy.jp]
ip = "10.0.0.2"
remark = "SSR JP"

[ruleset.direct]
rules = [
  "GEOIP, CN, DIRECT",
  "DOMAIN-SUFFIX, cn, DIRECT"
]

[ruleset.google]
rules = [
  "DOMAIN-MATCH, google, PROXY"
]
```
